### ISSUE TITLE
Remove Manta Registry

### ISSUE THREAD

**Issue by tanhauhau** [tanhauhau/manta-style#1]
- [x] LazyTypeAliasDeclaration
  - [x] lazily initialize the `TypeAliasDeclaration`
  - [x] ~~hoist all declaration of `LazyTypeAliasDeclaration` to the start of the file~~
- [x] manta-helpers
  - [x] List all the built-in helper type
  - [x] ~~Only import built-in helper type when used.~~

**Comment by Cryrivers** [comment]
Closing
